### ISSUE TITLE
'nepho stack status theforeman development' fails if there's nothing running

### ISSUE THREAD

**Issue by tfhartmann** [huit/nepho#100]
``` Shell
(nepho)[alaric@dhcp-128-103-62-80 nepho]$ nepho stack status theforeman development
A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.
Traceback (most recent call last):
  File "/Users/alaric/.virtualenvs/nepho/bin/nepho", line 8, in <module>
    execfile(__file__)
  File "/Users/alaric/Projects/nepho/bin/nepho", line 26, in <module>
    sys.exit(main())
  File "/Users/alaric/Projects/nepho/bin/nepho", line 21, in main
    app.run()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.0.2-py2.7.egg/cement/core/foundation.py", line 451, in run
    self.controller._dispatch()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.0.2-py2.7.egg/cement/core/controller.py", line 340, in _dispatch
    getattr(self, func['label'])()
  File "/Users/alaric/Projects/nepho/nepho/cli/stack.py", line 132, in status
    status = scene.get_provider().status()
  File "/Users/alaric/Projects/nepho/nepho/providers/vagrant_provider.py", line 50, in status
    status = v.status()
  File "build/bdist.macosx-10.9-intel/egg/vagrant.py", line 242, in status
  File "build/bdist.macosx-10.9-intel/egg/vagrant.py", line 523, in _run_vagrant_command
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'status']' returned non-zero exit status 1
(nepho)[alaric@dhcp-128-103-62-80 nepho]$ 
```

**Comment by robparrott** [comment]
We need to catch the error and print a sane output o the user.

**Comment by tfhartmann** [comment]
Looks like https://github.com/huit/nepho/pull/130  Cleared this up!
