### ISSUE TITLE
cloudlet update backtrace

### ISSUE THREAD

**Issue by robparrott** [huit/nepho#161]
I'm seeing the following:

```
± |master ✓| → ./bin/nepho cloudlet update nepho-example
Using default command scope nepho-example development-aws

Updating cloudlet: /Users/parrott/.nepho/cloudlets/nepho-example
Traceback (most recent call last):
  File "./bin/nepho", line 29, in <module>
    sys.exit(main())
  File "./bin/nepho", line 24, in main
    app.run()
  File     "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/foundation.py", line 493, in run
self.controller._dispatch()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/controller.py", line 448, in _dispatch
func()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/controller.py", line 454, in _dispatch
    func()
  File "/Users/parrott/Development/nepho/nepho/cli/cloudlet.py", line 179, in update
c.update()
  File "/Users/parrott/Development/nepho/nepho/core/cloudlet.py", line 99, in update
repo.remotes.origin.pull()
  File "/usr/local/lib/python2.7/site-packages/git/remote.py", line 605, in pull
return self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/usr/local/lib/python2.7/site-packages/git/remote.py", line 539, in _get_fetch_info_from_stderr
    assert len(fetch_info_lines) == len(fetch_head_info), "len(%s) != len(%s)" % (fetch_head_info, fetch_info_lines)
AssertionError: len(["abfaacac1f18a41b3742f5804f75dda2d9e765bb\t\tbranch 'master' of github.com:cloudlets/nepho-example\n", "3433ec97a6ff5027aff7b07d9ab18164bea025a1\tnot-for-merge\tbranch 'feature/development-aws' of github.com:cloudlets/nepho-example\n"]) != len(['Host key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48', '+--[ RSA 2048]----+', '|        .        |', '|       + .       |', '|      . B .      |', '|     o * +       |', '|    X * S        |', '|   + O o . .     |', '|    .   E . o    |', '|       . . o     |', '|        . .      |', '+-----------------+', '', '', 'X11 forwarding request failed on channel 0', '', ' = [up to date]      master     -> origin/master', ' = [up to date]      feature/development-aws -> origin/feature/development-aws'])
```

**Comment by hakamadare** [comment]
this is a consequence of cloudlets/nepho-example#8 - uninstall and reinstall the nepho-example cloudlet to fix it.
