### ISSUE TITLE
traceback from `nepho cloudlet search`

### ISSUE THREAD

**Issue by hakamadare** [huit/nepho#167]
```
======================================================================
ERROR: test_nepho_cloudlet_search (tests.cloudlet_test.a_TestNephoCloudlet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/huit/python/nepho/nepho/tests/cloudlet_test.py", line 57, in test_nepho_cloudlet_search
    app.run()
  File "/Users/huit/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/foundation.py", line 493, in run
    self.controller._dispatch()
  File "/Users/huit/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/controller.py", line 448, in _dispatch
    func()
  File "/Users/huit/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/controller.py", line 454, in _dispatch
    func()
  File "/Users/huit/python/nepho/nepho/nepho/cli/cloudlet.py", line 117, in search
    if (query == '') or (query.trim() in flattenedText):
AttributeError: 'str' object has no attribute 'trim'
-------------------- >> begin captured stdout << ---------------------
Updating cloudlet registry from: http://cloudlets.github.io/registry-dev.yaml

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): cloudlets.github.io
requests.packages.urllib3.connectionpool: DEBUG: "GET /registry-dev.yaml HTTP/1.1" 200 2053
--------------------- >> end captured logging << ---------------------
```

**Comment by robparrott** [comment]
Answer:  trim() -> strip()
