### ISSUE TITLE
`nepho stack show-template` doesn't handle Vagrantfiles

### ISSUE THREAD

**Issue by hakamadare** [huit/nepho#168]
```
======================================================================
ERROR: test_nepho_stack_show_template (tests.stack_test.a_TestNephoStack)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/huit/python/nepho/nepho/tests/stack_test.py", line 96, in test_nepho_stack_show_template
    app.run()
  File "/Users/huit/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/foundation.py", line 493, in run
    self.controller._dispatch()
  File "/Users/huit/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/controller.py", line 448, in _dispatch
    func()
  File "/Users/huit/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/controller.py", line 454, in _dispatch
    func()
  File "/Users/huit/python/nepho/nepho/nepho/cli/stack.py", line 64, in show_template
    print scene.template
  File "/Users/huit/python/nepho/nepho/nepho/core/scenario.py", line 88, in template
    jinja_template = jinja_env.get_template(template_filename)
  File "/Users/huit/.virtualenvs/nepho/lib/python2.7/site-packages/Jinja2-2.7.1-py2.7.egg/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/huit/.virtualenvs/nepho/lib/python2.7/site-packages/Jinja2-2.7.1-py2.7.egg/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/huit/.virtualenvs/nepho/lib/python2.7/site-packages/Jinja2-2.7.1-py2.7.egg/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/huit/.virtualenvs/nepho/lib/python2.7/site-packages/Jinja2-2.7.1-py2.7.egg/jinja2/loaders.py", line 178, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: Vagrantfile

----------------------------------------------------------------------
```

my first thought is that show-template needs to be provider-aware and just dump the Vagrantfile under Vagrant (no Jinja).

**Comment by robparrott** [comment]
How about putting the vagrant file in the standard place.

**Comment by robparrott** [comment]
Ok, forget that. Everything's changed again.

**Comment by agperson** [comment]
Sorry, this was an intentional decision, but the command should fail gracefully.  Functionality tracked as #169.
