### ISSUE TITLE
all nepho commands blow up when Vagrant not installed

### ISSUE THREAD

**Issue by hakamadare** [huit/nepho#206]
```
[root@logus ~]# nepho --help
Traceback (most recent call last):
  File "/usr/bin/nepho", line 9, in <module>
    load_entry_point('nepho==1.0.1rc6', 'console_scripts', 'nepho')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/nepho/cli/__init__.py", line 5, in <module>
    import stack
  File "/usr/lib/python2.6/site-packages/nepho/cli/stack.py", line 14, in <module>
    from nepho.core import common, cloudlet, stack, provider, provider_factory, scenario, parameter
  File "/usr/lib/python2.6/site-packages/nepho/core/provider_factory.py", line 2, in <module>
    from nepho.providers import vagrant_provider, aws_provider
  File "/usr/lib/python2.6/site-packages/nepho/providers/vagrant_provider.py", line 9, in <module>
    import vagrant
  File "/usr/lib/python2.6/site-packages/vagrant.py", line 103, in <module>
    'Please check if it is in the system path.')
AssertionError: The Vagrant executable cannot be found. Please check if it is in the system path.
```

at the very list we should catch that exception, print a nice error message, and give the user a link to the Vagrant website.

**Comment by agperson** [comment]
#237 should address this.
