### ISSUE TITLE
Deleting a deploy that doesn't exist throws uglyness 

### ISSUE THREAD

**Issue by tfhartmann** [huit/nepho#67]
``` Shell
(nepho)[alaric@preator nepho]$ nepho -E development -N tfhartmann delete openstack-grizzly
Traceback (most recent call last):
  File "/Users/alaric/.virtualenvs/nepho/bin/nepho", line 8, in <module>
    execfile(__file__)
  File "/Users/alaric/Projects/nepho/bin/nepho", line 23, in <module>
    sys.exit(main())
  File "/Users/alaric/Projects/nepho/bin/nepho", line 19, in main
    return nepho.aws.clidriver.main(output)
  File "/Users/alaric/Projects/nepho/nepho/aws/clidriver.py", line 266, in main
    context = get_management_settings(configMap)      
  File "/Users/alaric/Projects/nepho/nepho/aws/clidriver.py", line 162, in get_management_settings
    user_data_scripts['management'] = load_user_data_script(mgmt_script_file)
  File "/Users/alaric/Projects/nepho/nepho/aws/clidriver.py", line 122, in load_user_data_script
    f = open(script_filename)
IOError: [Errno 2] No such file or directory: '/Users/alaric/Projects/nepho/nepho/data/deployments/scripts/grizzly.sh'
```

**Comment by agperson** [comment]
Fixed a completely unrelated but with the same effect.
