### ISSUE TITLE
Implement "stack list" command

### ISSUE THREAD

**Issue by agperson** [huit/nepho#84]
- List all "active" stacks from internal state file

Optional/follow-up:
- Define a standard way of documenting/exposing interface points (i.e. SSH, Tier 1 URL, etc.)
- How to manage stacks that are modified outside of Nepho?
  - Query CloudFormation for AWS?
  - Query Vagrant state?
  - What else?

**Comment by tfhartmann** [comment]
Currently getting this 

``` Shell
(nepho)[alaric@dhcp-128-103-62-80 nepho]$ nepho stack list
Traceback (most recent call last):
  File "/Users/alaric/.virtualenvs/nepho/bin/nepho", line 10, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/alaric/Projects/nepho/bin/nepho", line 25, in <module>
    sys.exit(main())
  File "/Users/alaric/Projects/nepho/bin/nepho", line 20, in main
    app.run()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.0.2-py2.7.egg/cement/core/foundation.py", line 451, in run
    self.controller._dispatch()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.0.2-py2.7.egg/cement/core/controller.py", line 340, in _dispatch
    getattr(self, func['label'])()
  File "/Users/alaric/Projects/nepho/nepho/cli/stack.py", line 119, in list
    print dedent("""
NameError: global name 'dedent' is not defined
```

**Comment by robparrott** [comment]
The stack trace should be fixed now, but listing is still an outstanding issue.

**Comment by hakamadare** [comment]
again, good enough for 1.0.0.  more fixes in 1.1.0.
